multiples features
lhohenrique/AgendaUWP pull request #6
Opened 2019-11-19 18:33 UTC by ericmoraess

This pull request contains: 

- Create List Contact.
- Implements Add Contact Service.
- New Layers: Service and Data.

2019-11-19 19:18 UTC, lhohenrique requested changes

2019-11-19 19:18 UTC, lhohenrique commented on AgendaUWP/Service/Model/Contact.cs
> +        public Contact(string FullName, string NickName, int Age, string Phone, BitmapImage Photo)
The Photo parameter is passed but never assigned

2019-11-19 19:18 UTC, lhohenrique commented on AgendaUWP/Service/Contact/ContactService.cs
> +            return new List<Model.Contact>()
This code is still necessary?

2019-11-19 19:22 UTC, lhohenrique approved these changes

2019-11-20 16:57 UTC, soutolucas approved these changes

2019-11-20 16:57 UTC, merged